### ISSUE TITLE
make sure test workaround is sane

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/fluent-plugin-honeycomb#12]
@emfree Please make sure to take a look at https://github.com/honeycombio/fluent-plugin-honeycomb/commit/6b5b6eb6d6354e9ccfdd3a6f0fd5f39791be306f when you get back. it's probably fine but I am not a Fluent expert. Cheers

**Comment by emfree** [comment]
Thanks for digging into this Nathan! This looks good. To be future-proof, the version check in the tests should maybe be 
```
if Gem.loaded_specs['fluentd'].version > Gem::Version.new('0.12')
```
instead of 
```
if Gem.loaded_specs['fluentd'].version > Gem::Version.new('0.12.42')
```
but that's a tiny detail.

To try to clarify a bit what I think happened here: this plugin was supposed to target fluentd version 0.12, which at the time was the "stable" version. (That was also the version used in the Kubernetes addon until very recently.)

However, I fumbled the version constraint (here: https://github.com/honeycombio/fluent-plugin-honeycomb/blob/master/fluent-plugin-honeycomb.gemspec#L20), so in practice the unit tests actually ended up running against fluentd v0.14, as long as they were using Ruby 2.1 or greater. 

Ideally we'd document what versions of fluentd we support, and explicitly test with those. Opened #13 to track that.

**Comment by nathanleclaire** [comment]
👍
