### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/fluent-plugin-honeycomb#26]
After removing TravisCI in #25, we should setup CircleCI instead.

**Comment by JamieDanielson** [comment]
Closing this issue.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
